server:
  port: 8089

spring:
  application:
    name: sba-service
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    discovery:
      enabled: true
    config:
      client:
        oauth2:
          client-id: sb3-config-client
          client-secret: yCKT1xCZEc3oObmFEeZmL7TqpnZEdO53
          access-token-uri: http://localhost:8180/realms/sb3-keycloak/protocol/openid-connect/token
#      discovery:
#        enabled: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8180/realms/sb3-keycloak
#          jwk-set-uri: http://localhost:8180/realms/sb3-keycloak/protocol/openid-connect/certs
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8180/realms/sb3-keycloak
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-name: keycloak
#            client-id: sb3-sba-ui
#            authorization-grant-type: authorization_code
#            scope:
#              - "openid"
#  boot:
#    admin:
#      discovery:
#        enabled: true


eureka:
  client:
    enabled: true
    webclient:
      enabled: true
    oauth2:
      client-id: sb3-eureka-client
      client-secret: f8J8ynDQWNd6yh5Os8HZM0I7s3n8FONE
      access-token-uri: http://localhost:8180/realms/sb3-keycloak/protocol/openid-connect/token
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
#    org.springframework.security: debug
    org.pksprojects.sb3keycloak.sbaservice: debug
    org.springframework.cloud.config: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
      #include: health,info
